const ApiEndPoint = {
  API: "api",
  LOGIN: "/auth",
  LOG_OUT: "auth/logout",
  REFRESHTOKEN: "/auth/refresh-token",
  SENDCODEEMAIL: "/user/forgot-password",
  NEWPASSWORD: "user/reset-password",
  CREATE_IMPORT_ORDER: "api/manage-import-orders/create",
  ALLIMPORTORDER: "/api/manage-import-orders/getallImportOrder",
  ALLHISTORYIMPORTORDER: "/api/manage-import-orders/allDetails/merged-sku",
  ALLDETAILIMPORTORDER: "/api/manage-import-orders/allDetails",
  ALLEXPORTORDER: "/admin/export-orders/getallExportOrder",
  ALLEXPORTORDERDETAILS: "/admin/export-orders/getAllExportOrderDetails",
  EXPORTORDERDETAILBYID: "/admin/export-orders/detail",
  EXPORTORDERDETAILFULLBYID: "/admin/export-orders/detail",
  EXPORTORDERFULLBYID: "/admin/export-orders",
  SEARCHEXPORTORDERS: "/admin/export-orders/search",
  SEARCHEXPORTORDERSFULL: "/admin/export-orders/search-full",
  SEARCHEXPORTORDERSBOARD: "/admin/export-orders/search-board",
  EXPORTORDERBOARDDETAILS: "/admin/export-orders/getAllExportOrder/board",
  SKUSTATUSEXPORT: "/admin/export-orders/sku-status",
  MOVETOQUEUE: "/admin/export-orders/multiple/move-to-queue",
  MOVEBACKFROMQUEUE: "/admin/export-orders/multiple/move-back-from-queue",
  EXPORTWITHROUTE: "/admin/export-orders/multiple/export-with-route",
  IMPORT_CHART: "/api/dashboard/import-chart",
  EXPORT_CHART: "/api/dashboard/export-chart",
  SUMMARY_CHART: "/api/dashboard/summary-chart",
  SKU_TYPE_RATIO: "/api/dashboard/sku-type-ratio",
  OPTIMIZATION_INDEX: "/api/dashboard/optimization-index",
  STORAGE_STATUS: "/api/dashboard/storage-status",
  WAREHOUSE_SUMMARY_PDF: "/api/dashboard/warehouse-summary-pdf",
  UPLOADFILEEXCEL: "api/manage-import-orders/upload-excel-to-temp",
  TEMPITEMSTEMPORARY: "api/manage-import-orders/temp-items",
  DELETETEMPORARY: "api/manage-import-orders/delete/temp",
  UPDATETEMPORARY: "api/manage-import-orders/temp/update",
  IMPORTWAREHOUSE: "/api/manage-import-orders/import-from-temp",
  DOWNLOADTEMPLATEIMPORTORDER: "api/manage-import-orders/template",
  HISTORY_IMPORT_ORDER_BY_ID: "/api/manage-import-orders/import-orders",
  GET_ALL_SHELVES: "api/shelves/all",
  GET_BIN: "api/bins",
  GET_BOX: "api/boxes/bin",
  GET_DETAIL_SHELVES: "api/shelves",
  GET_DETAIL_BOX: "api/boxes",
  CREATE_SHELVES: "api/shelves/create",
  CHART_IMPORT: "api/dashboard/1.2-import-chart",
  CHART_EXPORT: "api/dashboard/2.2-export-chart",
  STORAGE_CHART: "api/dashboard/3.3-storage-shelf-chart",
  ERROR_CHART: "api/dashboard/4.2-trend",
  STORAGE_DONUT: "api/dashboard/3.2-storage-donut",
<<<<<<< HEAD
  // Product/SKU endpoints
  GET_ALL_SKUS: "/api/skus",
  SEARCH_SKUS: "/api/skus/search",
  GET_SKU_BY_ID: "/api/skus/getById",
  // Error Product/SKU endpoints (damaged products)
  GET_ALL_ERROR_SKUS: "/api/skus/damaged",
  SEARCH_ERROR_SKUS: "/api/skus/damaged/search",
  GET_ERROR_SKU_BY_ID: "/api/skus/damaged",
=======
  KPI_DASHBOARD: "api/dashboard/Full4KPI",
>>>>>>> WMS-04
};

export default ApiEndPoint;
