class StockInKeys {
  static readonly GETALLIMPORTORDER = "GETALLIMPORTORDER";
  static readonly GETALLHISTORYIMPORTORDER = "GETALLHISTORYIMPORTORDER";
  static readonly GETALLDETAILIMPORTORDER = "GETALLDETAILIMPORTORDER";
  static readonly UPLOADFILEEXCEL = "UPLOADFILEEXCEL";
  static readonly TEMPITEMSTEMPORARY = "TEMPITEMSTEMPORARY";
  static readonly DELETETEMPORARY = "DELETETEMPORARY";
  static readonly UPDATETEMPORARY = "UPDATETEMPORARY";
  static readonly IMPORTWAREHOUSE = "IMPORTWAREHOUSE";
  static readonly DOWNLOADTEMPLATEIMPORTORDER = "DOWNLOADTEMPLATEIMPORTORDER";
  static readonly HISTORY_IMPORT_ORDER_BY_ID = "HISTORY_IMPORT_ORDER_BY_ID";
  static readonly CREATE_IMPORT_ORDER = "CREATE_IMPORT_ORDER";
  static readonly SEARCH_IMPORT_ORDER = "SEARCH_IMPORT_ORDER";
  static readonly SEARCH_IMPORT_HISTORY = "SEARCH_IMPORT_HISTORY";
  static readonly DOWNLOAD_REPORT_EXCEL = "DOWNLOAD_REPORT_EXCEL";
}

export default StockInKeys;
