class StockInKeys {
  static readonly GETALLIMPORTORDER = "GETALLIMPORTORDER";
  static readonly GETALLHISTORYIMPORTORDER = "GETALLHISTORYIMPORTORDER";
  static readonly GETALLDETAILIMPORTORDER = "GETALLDETAILIMPORTORDER";
  static readonly UPLOADFILEEXCEL = "UPLOADFILEEXCEL";
  static readonly TEMPITEMSTEMPORARY = "TEMPITEMSTEMPORARY";
  static readonly DELETETEMPORARY = "DELETETEMPORARY";
  static readonly UPDATETEMPORARY = "UPDATETEMPORARY";
  static readonly IMPORTWAREHOUSE = "IMPORTWAREHOUSE";
  static readonly DOWNLOADTEMPLATEIMPORTORDER = "DOWNLOADTEMPLATEIMPORTORDER";
  static readonly HISTORY_IMPORT_ORDER_BY_ID = "HISTORY_IMPORT_ORDER_BY_ID";
}

export default StockInKeys;
