class StockInKeys {
  static readonly GETALLIMPORTORDER = "GETALLIMPORTORDER";
  static readonly GETALLDETAILIMPORTORDER = "GETALLDETAILIMPORTORDER";
  static readonly UPLOADFILEEXCEL = "UPLOADFILEEXCEL";
  static readonly TEMPITEMSTEMPORARY = "TEMPITEMSTEMPORARY";
  static readonly DELETETEMPORARY = "DELETETEMPORARY";
  static readonly UPDATETEMPORARY = "UPDATETEMPORARY";
  static readonly IMPORTWAREHOUSE = "IMPORTWAREHOUSE";
  static readonly DOWNLOADTEMPLATEIMPORTORDER = "DOWNLOADTEMPLATEIMPORTORDER";
}

export default StockInKeys;
