class StockOutKeys {
  static readonly GETALLEXPORTORDER = "GETALLEXPORTORDER";
  static readonly GETALLEXPORTORDERDETAILS = "GETALLEXPORTORDERDETAILS";
  static readonly GETEXPORTORDERDETAILBYID = "GETEXPORTORDERDETAILBYID";
  static readonly GETEXPORTORDERDETAILFULLYDETAILID =
    "GETEXPORTORDERDETAILFULLYDETAILID";
  static readonly GETEXPORTORDERBOARDDETAILS = "GETEXPORTORDERBOARDDETAILS";
  static readonly SEARCHEXPORTORDERS = "SEARCHEXPORTORDERS";
  static readonly GETEXPORTORDERBYID = "GETEXPORTORDERBYID";
  static readonly EXPORT_ORDER_FULL_BY_ID = "EXPORT_ORDER_FULL_BY_ID";
  // Search-specific keys
  static readonly SEARCH_EXPORT_ORDERS_WITH_FILTERS =
    "SEARCH_EXPORT_ORDERS_WITH_FILTERS";
}

export default StockOutKeys;
