class StockOutKeys {
  static readonly GETALLEXPORTORDER = "GETALLEXPORTORDER";
  static readonly GETALLEXPORTORDERDETAILS = "GETALLEXPORTORDERDETAILS";
  static readonly SEARCHEXPORTORDERS = "SEARCHEXPORTORDERS";
  static readonly GETEXPORTORDERBYID = "GETEXPORTORDERBYID";
  static readonly GETEXPORTORDERBOARDDETAILS = "GETEXPORTORDERBOARDDETAILS";
  // Search-specific keys
  static readonly SEARCH_EXPORT_ORDERS_WITH_FILTERS =
    "SEARCH_EXPORT_ORDERS_WITH_FILTERS";
}

export default StockOutKeys;
